### ISSUE TITLE
<OutputVelocityMax> Tag

### ISSUE THREAD

**Issue by icetiger1974** [floodmodel/G2D#5]
Hello

G2D File version: 2022.2.14

I changed 
\<OutputVelocityMax\>true\</OutputVelocityMax\>

so 
\<OutputDepth>true\</OutputDepth\>
\<OutputPrecision_Depth>5\</OutputPrecision_Depth\>
\<OutputWaterLevel>false\</OutputWaterLevel\>
\<OutputPrecision_WaterLevel>5\</OutputPrecision_WaterLevel\>
\<OutputVelocityMax>true\</OutputVelocityMax\>
\<OutputPrecision_VelocityMax>5\</OutputPrecision_VelocityMax\>
\<OutputDischargeMax>false\</OutputDischargeMax\>
\<OutputPrecision_DischargeMax>2\</OutputPrecision_DischargeMax\>
\<OutputFDofMaxV>true\</OutputFDofMaxV\>

However, there is no Velocity out file.
There are only depth and FD files.
 
![image](https://user-images.githubusercontent.com/3273375/161029469-821b1784-83c0-48e1-a4ca-02f942cb2096.png)

Best regards
YJ Won

**Comment by yschoi51** [comment]
Hi, icetiger
The previous version of the G2D model was inactivated making Max. velocity output files.
I have uploaded the new version (file version 2022.04.01 and later) of the model to activate making Max. velocity output files.
Please use the new version model (G2D.exe) at https://github.com/floodmodel/G2D/tree/master/DownloadStableVersion
